---
- hosts: STAGING_CTRL_SERVER
  become: true
  tasks:
    - name: Add epel-release repo
      yum: 
        name: epel-release
        state: present
    - name: ensure nginx is at the latest version
      yum: name=nginx state=latest
    - name: start nginx
      service: 
          name: nginx
          state: started
    - name: Insert index Page
      template:
              src: index.html
              dest: /usr/share/nginx/html/index.html
    - name: restart nginx
      service:
              name: nginx
              state: restarted
