---
# tasks file for configure_replication_host2
- name: configure mariadb cnf file on host2
  blockinfile:
          path: /etc/my.cnf
          block: |
           [mariadb]
            server-id=2
            log-bin=mysql-bin
            bind-address=0.0.0.0
          insertbefore: BOF

- name: restart mariadb on host2
  service:
        name: mariadb
        state: restarted

- name: create user for replication on host1
  mysql_user:
     login_user: 'root'
     login_password: 'test2020'
     name: 'repl'
     password: 'test2020'
     host: "%"
     encrypted: no
     priv: '*.*:ALL,GRANT'
     state: present

- name: stop slave
  shell:
    cmd: mysql --user=root --password=test2020 -e "STOP SLAVE"


- name: Setup replication
  shell:
    cmd: mysql --user=root --password=test2020 -e "CHANGE MASTER TO master_host='192.168.33.10', master_user='repl', master_password='test2020', master_use_gtid=current_pos"

- name: Restart mysql service
  service: name=mariadb  state=restarted
     


#- mysql_replication:
# login_host: localhost
# login_port: 3306
# login_user: 'repl'
# login_password: 'test2020'
# mode: stopslave

# Get master binlog file name and binlog position
#- mysql_replication:
# login_host: localhost
# login_port: 3306
# login_user: 'repl'
# login_password: 'test2020'
# mode: getmaster

# Change master to master server 192.0.2.1 and use binary log 'mysql-bin.000009' with position 4578
#- mysql_replication:
# login_host: localhost
# login_port: 3306
# login_user: 'repl'
# login_password: 'test2020'
# mode: changemaster
# master_host: 192.168.33.10
# master_log_file: mysql-bin.000008
# master_log_pos: 4577


